src/Entity/ContainerShip.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ContainerShipRepository")
 * @ORM\Table(name="CONTAINERSHIP")
 */
class ContainerShip
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $captain_name;

    /**
     * @ORM\Column(type="integer")
     */
    private $container_limit;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * @return mixed
     */
    public function getCaptainName()
    {
        return $this->captain_name;
    }

    /**
     * @param mixed $captain_name
     */
    public function setCaptainName($captain_name)
    {
        $this->captain_name = $captain_name;
    }

    /**
     * @return mixed
     */
    public function getContainerLimit()
    {
        return $this->container_limit;
    }

    /**
     * @param mixed $container_limit
     */
    public function setContainerLimit($container_limit)
    {
        $this->container_limit = $container_limit;
    }


    public function __toString()
    {
        if ($this->name) {
            return $this->name;
        }
        return 'ContainerShip without name';
    }


}

src/Controller/ContainerShipController.php
<?php

namespace App\Controller;

use App\Service\ContainerShipService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ContainerShipController extends AbstractController
{
    /**
     * @Route("/containership", name="containership")
     * @param ContainerShipService $containerShipService
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function containerShipAction(ContainerShipService $containerShipService): \Symfony\Component\HttpFoundation\Response
    {
        $containerShips = $containerShipService->getContainerShips();
        return $this->render('ContainerShip/containerShips.html.twig', array(
            'containerShips' => $containerShips
        ));
    }

    /**
     * @Route("/containership/{id}", name="containership_info")
     * @param ContainerShipService $containerShipService
     * @param int $id
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function containerShipIdAction(ContainerShipService $containerShipService, int $id): \Symfony\Component\HttpFoundation\Response
    {
        $containerShip = $containerShipService->getContainerShipById($id);
        return $this->render('ContainerShip/containership_info.html.twig', array(
            'containerShip' => $containerShip
        ));
    }

    /**
     * @Route("/containership/new/", name="containership_new")
     * @param Request $request
     * @param ContainerShipService $containerShipService
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function containerShipNewAction(Request $request, ContainerShipService $containerShipService)
    {
        if ($request->getMethod() === 'POST') {
            $containerShip = $containerShipService->addContainerShip($request);
            return $this->redirectToRoute('containership_info', array('id' => $containerShip->getId()));
        }

        return $this->render('ContainerShip/containership_add.html.twig');
    }

}

templates/ContainerShip/containerShips.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <section>
        <div class="container">

            <h1>Tous les container ships</h1>

            <a href="{{ path('containership_new') }}" class="btn btn-success"><i class="fa fa-plus mr-2"></i>Ajouter un ContainerShip</a>

            <table class="table mt-5">
                <thead class="thead-dark">
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Nom du capitaine</th>
                    <th>Limite</th>
                    <th>Voir</th>
                </tr>
                </thead>

                {% for containerShip in containerShips %}
                    <tr>
                        <th scope="row">{{ containerShip.id }}</th>
                        <td>{{ containerShip.name }}</td>
                        <td>{{ containerShip.captainName }}</td>
                        <td>{{ containerShip.containerLimit }}</td>
                        <td><a href="{{ path('containership_info', { 'id' : containerShip.id }) }}" class="btn btn-primary"><i class="fa fa-eye mr-2"></i>Voir</a></td>
                    </tr>
                {% endfor %}

            </table>

        </div>
    </section>

{% endblock %}

templates/ContainerShip/containership_add.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <section>
        <div class="container">

            <form method="post" class="col col-lg-6 mx-auto">

                <h1 class="mb-5">Ajouter un containerShip</h1>

                <div class="form-group">
                    <label for="">Nom du ContainerShip</label>
                    <input type="text" name="name" class="form-control">
                </div>

                <div class="form-group">
                    <label for="">Nom du Capitaine</label>
                    <input type="text" name="captain_name" class="form-control">
                </div>

                <div class="form-group">
                    <label for="">Limite du container</label>
                    <input type="number" name="container_limit" class="form-control">
                </div>

                <input type="submit" value="Enregistrer le containerShip" class="form-control btn btn-success">

            </form>

        </div>
    </section>

{% endblock %}

templates/ContainerShip/containership_info.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <section>
        <div class="container">

            <h1>ContainerShip n°{{ containerShip.id }}</h1>

            <table class="table mt-5">
                <thead class="thead-dark">
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Nom du capitaine</th>
                    <th>Limite</th>
                </tr>
                </thead>
                <tr>
                    <th scope="row">{{ containerShip.id }}</th>
                    <td>{{ containerShip.name }}</td>
                    <td>{{ containerShip.captainName }}</td>
                    <td>{{ containerShip.containerLimit }}</td>
                </tr>
            </table>

        </div>
    </section>

{% endblock %}